// use jag_core::errors::Result;
use jag_core::types::{Artifact, TaskId, CoverageReport};

/// Generates a professional PR description using the mission context.
/// In a real scenario, this would call the ModelRouter to generate a summary.
/// For the current phase, we provide a structured template.
pub fn generate_pr_description(
    mission_prompt: &str,
    mission_id: &TaskId,
    artifacts: &[Artifact],
    coverage: &CoverageReport,
    dashboard_url: &str,
) -> String {
    let mut artifact_list = String::new();
    for art in artifacts {
        artifact_list.push_str(&format!("- `{}` ({:?})\n", art.id, art.artifact_type));
    }

    format!(
        r#"# 🤖 AI-Generated Mission: {}

## Summary
{}

## 🛠️ Changes Contained
{}

## 🧪 Testing & Coverage
- **Rust Coverage**: {:.1}%
- **TypeScript Coverage**: {:.1}%
- **Status**: {}

---
*Generated by Jag IDE • [Mission Dashboard]({}/missions/{})*"#,
        mission_id,
        mission_prompt,
        artifact_list,
        coverage.rust_coverage * 100.0,
        coverage.ts_coverage * 100.0,
        if coverage.passed { "✅ Passed" } else { "❌ Blocked" },
        dashboard_url,
        mission_id
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use jag_core::types::TaskId;

    #[test]
    fn test_pr_description_generation() {
        let task_id = TaskId::new();
        let mission_prompt = "Implement auth middleware";
        let coverage = CoverageReport {
            rust_coverage: 0.85,
            ts_coverage: 0.88,
            passed: true,
            details: "All gates passed".into(),
        };

        let desc = generate_pr_description(
            mission_prompt,
            &task_id,
            &[],
            &coverage,
            "http://localhost:3000"
        );

        assert!(desc.contains("# 🤖 AI-Generated Mission"));
        assert!(desc.contains("**Rust Coverage**: 85.0%"));
    }
}
